<?php 

$bieres = [
    1 => [
        'nom' => "Souffle Sichuanais",
        'degre_d_alcool' => "5,5",
        'ingredients' => 'Ingrédients: Eau, Orge Malté (7,67%), Houblon Nelson Sauvin (0,17), Graines de coriandre (0,05%), Levures Nottingham (0,04%), Poivre de Sichuan (0,03%). ',
        'contenance' => '75cl',
        'prix' => '3€',
        'description' => "Bière blonde au poivre de Sichuan d'inspiration belge non filtrée non pasteurisée.", 
        'valeurs_nutritionnelles' => '',
        'disponibilite' => "oui",
        'photo' => '',
    ],
    2 => [
        'nom' => "Venin Sucré",
        'degre_d_alcool' => '7',
        'ingredients' => 'Ingrédients: Eau, Orge Malté (7,67%), Houblon Nelson Sauvin (0,17), Graines de coriandre (0,05%), Levures Nottingham (0,04%), Miel (0,03%).',
        'contenance' => '75cl',
        'prix' => '3€',
        'description' => "Bière ambrée miel d’inspiration belge non ﬁltrée non pasteurisée.", 
        'valeurs_nutritionnelles' => '56_seyma_acar.png',
        'disponibilite' => "oui",
        'photo' => '56_seyma_acar.png',
    ],
    3 => [
        'nom' => "Pavot Abyssal",
        'degre_d_alcool' => '6',
        'ingredients' => "Ingrédients: Eau, Orge Malté (7,67%), Houblon Nelson Sauvin (0,17), Graines de coriandre (0,05%), Levures Nottingham (0,04%), Fleur de Pavot (0,03%).",
        'contenance' => '75cl',
        'prix' => '3€',
        'description' => "Bière blanche au pavot bleu d’inspiration belge non ﬁltrée non pasteurisée.", 
        'valeurs_nutritionnelles' => '56_seyma_acar.png',
        'disponibilite' => "oui",
        'photo' => '56_seyma_acar.png',
    ],
    4 => [
        'nom' => "Lavande Cosmique",
        'degre_d_alcool' => "5",
        'ingredients' => 'Ingrédients: Eau, Orge Malté (7,67%), Houblon Nelson Sauvin (0,17), Graines de coriandre (0,05%), Levures Nottingham (0,04%), Lavande (0,03%).',
        'contenance' => '75cl',
        'prix' => '3€',
        'description' => "Bière brune à la lavande d’inspiration belge non ﬁltrée non pasteurisée.", 
        'valeurs_nutritionnelles' => '56_seyma_acar.png',
        'disponibilite' => "oui",
        'photo' => '56_seyma_acar.png',
    ],
    5 => [
        'nom' => "Menthe Celeste",
        'degre_d_alcool' => "6.0",
        'ingredients' => 'Ingrédients: eau 92,04%, malts, houblon 0,17%',
        'contenance' => '75cl',
        'prix' => '3€',
        'description' => "Bière ambrée mentholée d’inspiration belge non filtré", 
        'valeurs_nutritionnelles' => 'Contient du gluten',
        'disponibilite' => "oui",
        'photo' => 'public\images\pegase.png',
    ],
    6 => [
        'nom' => "Soleil Ardent",
        'degre_d_alcool' => '7',
        'ingredients' => "Ingrédients: Eau, Orge Malté (7,67%), Houblon Nelson Sauvin (0,17), Graines de coriandre (0,05%), Levures Nottingham (0,04%), Curry (0,03%).",
        'contenance' => '75cl',
        'prix' => '3€',
        'description' => "Bière blonde au curry d’inspiration belge non ﬁltrée non pasteurisée.", 
        'valeurs_nutritionnelles' => '56_seyma_acar.png',
        'disponibilite' => "oui",
        'photo' => '56_seyma_acar.png',
    ],
];