<?php 

$bieres = [
    1 => [
        'nom' => "Seyma",
        'degre_d_alcool' => "ACAR",
        'ingredients' => '13/07/2004',
        'contenance' => '56',
        'prix' => '56_seyma_acar.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
        'valeurs_nutritionnelles' => '56_seyma_acar.png',
        'disponibilite' => '56_seyma_acar.png',
        'photo' => '56_seyma_acar.png',
    ],
    2 => [
        'nom' => "Seyma",
        'degre_d_alcool' => "ACAR",
        'ingredients' => '13/07/2004',
        'contenance' => '56',
        'prix' => '56_seyma_acar.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
        'valeurs_nutritionnelles' => '56_seyma_acar.png',
        'disponibilite' => '56_seyma_acar.png',
        'photo' => '56_seyma_acar.png',
    ],
    3 => [
        'nom' => "Seyma",
        'degre_d_alcool' => "ACAR",
        'ingredients' => '13/07/2004',
        'contenance' => '56',
        'prix' => '56_seyma_acar.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
        'valeurs_nutritionnelles' => '56_seyma_acar.png',
        'disponibilite' => '56_seyma_acar.png',
        'photo' => '56_seyma_acar.png',
    ],
    4 => [
        'nom' => "Seyma",
        'degre_d_alcool' => "ACAR",
        'ingredients' => '13/07/2004',
        'contenance' => '56',
        'prix' => '56_seyma_acar.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
        'valeurs_nutritionnelles' => '56_seyma_acar.png',
        'disponibilite' => '56_seyma_acar.png',
        'photo' => '56_seyma_acar.png',
    ],
    5 => [
        'nom' => "Seyma",
        'degre_d_alcool' => "ACAR",
        'ingredients' => '13/07/2004',
        'contenance' => '56',
        'prix' => '56_seyma_acar.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
        'valeurs_nutritionnelles' => '56_seyma_acar.png',
        'disponibilite' => '56_seyma_acar.png',
        'photo' => '56_seyma_acar.png',
    ],
    6 => [
        'nom' => "Seyma",
        'degre_d_alcool' => "ACAR",
        'ingredients' => '13/07/2004',
        'contenance' => '56',
        'prix' => '56_seyma_acar.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
        'valeurs_nutritionnelles' => '56_seyma_acar.png',
        'disponibilite' => '56_seyma_acar.png',
        'photo' => '56_seyma_acar.png',
    ],
];